### ISSUE TITLE
Where is the latest version?

### ISSUE THREAD

**Issue by dyaskur** [jhonatasrm/chromium-android#2]
May I know where you get this source code? I was find on https://chromium.googlesource.com/ but not found something like this repo.

**Comment by jhonatasrm** [comment]
Hi there!
I was thinking of working on this in the past but without time... You can find more about the source [here](https://github.com/JackyAndroid/AndroidChromium) and also [here](https://github.com/kuoruan/Chromium-Android) (archived).

Hope it helps.
